# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='name',
        ),
    ]
