# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 06:04
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20170106_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='pho',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='photos'),
        ),
    ]
