# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 18:01
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_remove_album_pho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
