# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
