# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20170109_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='tag',
            new_name='tags',
        ),
    ]
