# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
