# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='익명', max_length=30)),
                ('title', models.CharField(max_length=220)),
                ('message', models.TextField(default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
