# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 16:09
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
