# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 08:03
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('bamboo', '0002_auto_20170105_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamboo',
            name='tags1',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
