# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.CharField(default='익명', max_length=30),
        ),
    ]
