# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20170113_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='pho',
        ),
    ]
