# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bamboo',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
